In [1]:
import pandas as pd
import numpy as np
from Modul._5_implementasi_algoritma import DWKNN, undersampling

In [2]:
import time
from warnings import filterwarnings
filterwarnings("ignore")

In [3]:
df_train = pd.read_csv('Output/3_Feature_Extraction/train.csv')
df_test = pd.read_csv('Output/3_Feature_Extraction/test.csv')
display(df_train)
display(df_test)

      sentiment                                  text_preprocessed
0            -1  presiden hebat anies capai lihat ganjar prabow...
1             0  tuju tangkal anies kemarin biar anies omong ad...
2             0  doa tiga malam dok laku nama anies muhaiminkan...
3             0  bude pakai etika pas duo cawapres serang bocil...
4             1  ganjar mahfud paham petugas pajak integritas k...
...         ...                                                ...
6976          1  calon wakil presiden cawapres nomor urut muhai...
6977          1                       deh hebat gibran diam tonton
6978          1                 mampu pimpin mas gibran ragu hebat
6979          0  singkat anies tutup wawancara pers debat termi...
6980          0       amin anies baswedan muhaimin iskandar sa via

[6981 rows x 2 columns]

      sentiment                                  text_preprocessed
0             0  halo debat capres dunia peserta nya nilai turu...
1             1                         anies efek gus imin cerdas
2            -1                         malu walikota model gibran
3             0  capresnya singgung etika anies wakil etika mah...
4             1  mas gibran pimpin cerdas rakyat sukses mas gib...
...         ...                                                ...
1868          0  surat mandat teman saksi pulang aji rutin kah ...
1869          0  lupa info rekan rekan guru honorer iya rekam j...
1870          1  investor harga upaya ganjar mahfud cipta trans...
1871          0  tkn prabowo gibran hampir moderator debat kpu ...
1872          0  gilir gibran katai sombong lihat anies ganjar ...

[1873 rows x 2 columns]

In [4]:
tfidf_df_train = pd.read_parquet('Output/3_Feature_Extraction/train_tfidf.parquet')
tfidf_df_test = pd.read_parquet('Output/3_Feature_Extraction/test_tfidf.parquet')
display(tfidf_df_train)
display(tfidf_df_test)

,aa,aamiin,abad,abadi,abah,abai,abal,abang,abangan,abdee,...,zikir,zionis,zjk,zodiak,zon,zona,zonk,zul,zulhas,zulkifli
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6976,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6977,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6978,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6979,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6980,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

,aa,abadi,abah,abai,abal,abang,abdi,abdul,abu,acah,...,zainal,zakir,zalim,zaman,zar,zidane,zionis,zon,zulhas,zulkifli
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1868,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1869,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1870,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1871,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1872,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
X_train = tfidf_df_train
X_test = tfidf_df_test
y_train = df_train['sentiment']
y_test = df_test['sentiment']

In [ ]:
X_train, y_train, X_test, y_test = undersampling(X_train, y_train, X_test, y_test)

In [7]:
X = pd.concat([X_train, X_test], ignore_index=False).fillna(0).reset_index(drop=True)
X_train = X.loc[:len(X_train)-1].reset_index(drop=True)
X_test = X.loc[len(X_train):].reset_index(drop=True)
display(X_train)
display(X_test)

,aa,aamiin,abad,abadi,abah,abai,abal,abang,abangan,abdee,...,wiki,wk,woilah,yarham,yennie,yerusalem,yohanes,yuana,zainal,zidane
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1318,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1319,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1320,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1321,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1322,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

,aa,aamiin,abad,abadi,abah,abai,abal,abang,abangan,abdee,...,wiki,wk,woilah,yarham,yennie,yerusalem,yohanes,yuana,zainal,zidane
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
337,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
338,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
339,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
340,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
341,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
X_train = np.array(X_train)
X_test = np.array(X_test)
y_train = np.array(y_train)
y_test = np.array(y_test)

In [9]:
for i in range(10):
  start = time.time()
  result = pd.DataFrame()
  n = (i+1)*5
  dwknn = DWKNN(k=n)
  dwknn.fit(X_train, y_train)
  y_predict = dwknn.predict(X_test)
  result[f'k_{n}'] = pd.Series(y_predict)
  result.to_csv(f'Output/5_Implementasi_Algoritma/DWKNN/Undersampling/result_k_{n:02}.csv', index=False)
  end = time.time()
  print(f"Running time: {end - start:.4f} seconds")

Running time: 27.6327 seconds
Running time: 27.5956 seconds
Running time: 29.4823 seconds
Running time: 37.8751 seconds
Running time: 31.1830 seconds
Running time: 30.6889 seconds
Running time: 30.8715 seconds
Running time: 30.6634 seconds
Running time: 30.8443 seconds
Running time: 31.2447 seconds

In [10]:
pd.DataFrame({'sentiment': y_test}).to_csv('Output/5_Implementasi_Algoritma/DWKNN/Undersampling/actual.csv', index=False)